<?= $block->getButtonHtml(); ?>
<div id="autoAddDataProduct" style="display:none;">
    <b><h3>Use this cron job to retrieve anynew images and mapped attribute metadata from DAMthat should sync to an Adobe Commerce product.</h3></b>
</div>
<div id="autoReplaceDataProduct" style="display:none;">
    <b><h3>Once any bynder user/members remove sku from selected meta properties that will be update to magento as well.</h3></b>
</div>
<div id="featchNullSKUToMagento" style="display:none;">
    <b><h3>Use this cron job to retrieve all images from DAMthat should sync to an Adobe Commerce product that currently has no other images</h3></b>
</div>
<div id="DeleteDataProduct" style="display:none;">
    <b><h3>Use this cron job to remove SKU and/or image role from DAMafter being removed from Adobe Commerce product.</h3></b>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Description',
                buttons: [{
                    text: $.mage.__('OK'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#autoAddDataProduct'));
            window.AutoAddDataProduct = function() {
                $('#autoAddDataProduct').modal('openModal');
            };
            
            var popup = modal(options, $('#autoReplaceDataProduct'));
            window.AutoReplaceDataProduct = function() {
                $('#autoReplaceDataProduct').modal('openModal');
            };
            
            var popup = modal(options, $('#featchNullSKUToMagento'));
            window.FeatchNullSKUToMagento = function() {
                $('#featchNullSKUToMagento').modal('openModal');
            };
            var popup = modal(options, $('#DeleteDataProduct'));
            window.DeleteDataProduct = function() {
                $('#DeleteDataProduct').modal('openModal');
            };
            
            
        }  
    );
</script>
