<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

?>

<div class="media-gallery-container">
	<button type="button" name="bynder" id="bynder_import" class="action- scalable media-gallery-actions-buttons">Import Bynder Image</button>
    <?= $block->getChildHtml(); ?>
</div>

<script type="text/x-magento-init">
    {
        ".media-gallery-container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "media_gallery_container": {
                        "component": "Magento_MediaGalleryUi/js/container",
                        "containerSelector": ".media-gallery-container",
                        "masonryComponentPath": "media_gallery_listing.media_gallery_listing.media_gallery_columns"
                    }
                }
            }
        }
    }
</script>


<div id="popup-modal-content" style="display:none;">
    <div id="compactViewContainer_content"></div>
</div>
<input type="hidden" id="ajax_baseurl" value="<?= $block->escapeUrl($block->getBaseUrl() . 'bynder/index'); ?>">
<input type="hidden" id="ajax_addtofolder" value="<?= $block->escapeUrl($block->getBaseUrl().'bynder/bynderindex');?>" >
<input type="hidden" id="form_keys" value="<?= $block->escapeHtml($block->getFormKey()); ?>">


<script>
require([
    'jquery',
    'Magento_Ui/js/modal/modal'
],
function($,modal) {
    var AjaxUrl = jQuery("#ajax_baseurl").val();
    var form_keys = jQuery("#form_keys").val();
	jQuery("#bynder_import").appendTo(jQuery('.modal-slide.magento._show').find('div .page-actions'));
    $('#bynder_import').on('click', function() {
        BynderCompactView.open({
            language: "en_US",
            theme: {
                colorButtonPrimary: "#3380FF"
            },
            /* mode:"SingleSelect", */
            assetTypes: ["image"],
            mode: "MultiSelect",
            onSuccess: function(assets, additionalInfo) {
                var server_response = bynder_function(assets, additionalInfo);
                if (server_response) {
                    return true;
                }
                else {
                    return false;
                }


				function bynder_function(assets, a) {
					var asset = assets[0];
					var dataset_ids = [];
					var dataset_type = [];

					$.each(assets, function (index, value) {
						dataset_ids.push(value.databaseId);
						dataset_type.push(value.type);
					});
					var bdomain = localStorage.getItem("cvad");
					if(typeof bdomain == "undefined" && bdomain == null) {
						alert("Something went wrong. Re-login system and try again...");
					}

					$.ajax({
						showLoader: true,
						url: AjaxUrl,
						type: "POST",
						data: {databaseId: dataset_ids, bdomain: bdomain, datasetType: dataset_type, form_key : form_keys },
						dataType: "json",
					}).done(function (data) {
						var total_images = 0;
						if (data.status == 2) {
							alert(data.message);
							return false;
						}
						else if (data.status == 1) {

							var type_design = "<style>"+
											".image-boxs {display: grid; grid-template-columns: repeat(5, 1fr); grid-column-gap: 5px;}"+
											".image-boxs .m-box"+
											"{border: 1px solid rgba(0, 0, 0, 0.8); margin: 3px; text-align: center; padding: 5px;}"+
											".m-content label { font-weight: 800; }"+
											"</style>";

							type_design += '<div class="main-part bynder-imgbox-div">' +
												'<div class="middle-content">' +
												'<div class="main-one image-boxs" >';

							$.each(data.data, function (index, r) {
								$.each(r, function (i, res) {
									var dataset_tag = '<img src="' + res.image_link + '">';
									total_images++;

									console.log("bynder step=1");
									console.log(res);

									if(res.dataset_type == "VIDEO") {
										dataset_tag = '<video width="100%" controls><source src="'+res.image_link+'" type="video/mp4">'
										dataset_tag +='<source src="'+res.main_link+'" type="video/ogg">'+
														'Your browser does not support HTML video.</video>';
									}

									var dataset_size = '( Size: ' + res.size + ')'
									if(res.dataset_type == "DOCUMENT") {
										dataset_size = " ";
									}

									type_design += '<div class="m-box">' +
											'<div class="m-img">' +
												dataset_tag +
											'</div>' +
											'<div class="m-content">' +
												'<input type="checkbox" class="image_types"'+
												'id="image_type_' + total_images + '"'+
												' name="image_type_'+index+'" value="' + res.type + index + '">' +
												'<label for="image_type_' +total_images+ '">' +res.type+" "+dataset_size+'</label>' +
											'</div>' +
											'</div>';
								});
							});
							type_design += '</div> </div> </div>';

							$("#compactViewContainer_content").html(type_design);
							var options = {
								type: "popup",
								responsive: true,
								innerScroll: true,
								title: "Select Bynder Image",
								buttons: [{
									text: $.mage.__("Continue"),
									id: "selected_item_btn",
									class: "",
									click: function () {
										var selected_types = [];
										$(".image_types").each(function () {
											var select_val = $(this).val();
											if ($(this).prop("checked")) {
												selected_types.push(select_val);
											}
										});

										if(selected_types.length > 0) {
											var img_url = "";
											var img_url_path = "";
											var database_array = [];
											$.each(data.data, function (index, r) {
												var image_links_test = assets[index].url;
												$.each(r, function (i, res) {
													image_links_test += "&&thumb_link=" + res.image_link + "&&"
													var type_val = res.type + index;
													if ($.inArray(type_val, selected_types) != -1) {
														console.log(res);

														if(res.dataset_type == "DOCUMENT") {
															img_url += res.image_link + "\n";
															img_url_path += res.image_link + ",";
															database_array.push(res.main_link);
														}
														else {
															if(res.dataset_type != "DOCUMENT") {
																img_url += res.image_link + "\n";
																img_url_path += res.image_link + ",";
																database_array.push(res.image_link);
																/*database_array.push(res.s3_link);*/
															}
														}
													}
												});
											});

											console.log(database_array);


											addtodirectory(database_array);
											this.closeModal();


										}
										else {
											alert("Sorry, you not selected any type ?");
										}
									}
								}]

							};
							var popup = modal(options, $("#popup-modal-content"));
							$("#popup-modal-content").modal("openModal");
							return true;

						} else {
							alert(data.message);
							return false;
						}
					});
				}


				function addtodirectory(img_data) {
					console.log("add dir");
					console.log(img_data);

					var callurl = $("#ajax_addtofolder").val();
					var form_keys = $("#form_keys").val();
					var dir_path = "Bynder_macfarlane";
					if(img_data != "") {
						$.ajax({
							showLoader: true,
							url: callurl,
							type: "POST",
							data: { img_data : img_data, form_key : form_keys, dir_path : dir_path },
							dataType: "json",
						}).done(function (data) {
							var res = data;
							console.log(data);
							if(res.status == 1) {
								if(jQuery('label[data-force_static_path="1"][data-bind*="openMediaBrowserDialog"]').length > 0) {
									console.log("IF");
									jQuery('label[data-force_static_path="1"][data-bind*="openMediaBrowserDialog"]').trigger('click')
									var successMessage = '<div class="message message-success success"><div data-ui-id="messages-message-success">Assets have been successfully uploaded!</div></div>';
									$('ul.messages').append(successMessage);
									$('ul.messages').find('.success').last().hide().fadeIn();
									setTimeout(function () {
										$('ul.messages').find('.success').fadeOut(function () {
											$(this).remove();
										});
									}, 5000); 
								}else {
									console.log("ELSE");
									jQuery('button.scalable.action-add-image.plugin').trigger('click')
									var successMessage = '<div class="message message-success success"><div data-ui-id="messages-message-success">Assets have been successfully uploaded!</div></div>';
									$('ul.messages').append(successMessage);
									$('ul.messages').find('.success').last().hide().fadeIn();
									setTimeout(function () {
										$('ul.messages').find('.success').fadeOut(function () {
											$(this).remove();
										});
									}, 5000); 
								}
								//jQuery('#YnluZGVy a').click();
								return true;
							} else {
								alert(res.message);
								return false;
							}
						});
					} else {
						alert("Something went wrong. Please reload the page and try again.");
						return false;
					}
				}
            }
        });
    });

});
</script>

